version: '3.8'

services:
  backend:
    build: ./backend
    container_name: node-backend
  
  frontend:
    build: ./frontend
    container_name: npm-frontend

  apache:
    build: ./apache
    container_name: apache-router
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
